### ISSUE TITLE
Widgets to fix colormap limits

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/xrviz#10]
We need widgets to fix the colormap limits.    This is useful for static maps, but is essential for animations, where you don't usually want the color limits changing from frame to frame.

**Comment by martindurant** [comment]
Agreed, will probably have a double-ended slider or two sliders for max/min, set to the global max/min of the array being plotted. Will eventually also want colour scaling (sqrt, sq, log, hist, 1/x ...).

**Comment by hdsingh** [comment]
This would be implemented in the style panel.

**Comment by hdsingh** [comment]
Widgets to fix the colormap limits and Colour scaling have been implemented in [Style panel PR #13](https://github.com/intake/xrviz/pull/13).
