### ISSUE TITLE
Web visualization

### ISSUE THREAD

**Issue by CommonClimate** [intake/xrviz#22]
Hello,

I'm interested in web-based visualization of netCDF data. Are there plans for xrviz to connect with a web front-end, both for locally-hosted netCDF files, or via OPeNDaP for remotely-hosted files? In any case, if you have not considered such applications of the tech, I encourage you to think about it, and will be happy to provide a use case or two!

Beyond visualization, I'd also like to facilitate export of the subset of data being plotted (either as netCDF, or a simpler format (say, csv) for 1D arrays.  Do you know of any package that does that? If not, what would be technical hurdles to consider?

Julien

**Comment by hdsingh** [comment]
Hi @CommonClimate,

>I'm interested in web-based visualization of netCDF data. Are there plans for xrviz to connect with a web front-end, both for locally-hosted netCDF files, or via OPeNDaP for remotely-hosted files? 

XrViz is already having web-based frontend in the sense that interface dashboard generated is displayed in the browser. You can easily visualise local and remote files by:
```python
import xarray as xr
from xrviz.dashboard import Dashboard

# for local data
file_name = 'file name/location here'
data = xr.open_dataset(file_name)

# for remote data
url = 'data url here'
data = xr.open_dataset(url)

dashboard = Dashboard(data)
dashboard.show()
```

**Comment by martindurant** [comment]
I would like to add, that the xrviz interface can be embedded in any Panel layout you might want, or, of course, be included in a site using standard HTML techniques. The former of these two options is the one which [intake](https://intake.readthedocs.io) plans to take, thus unifying the finding and loading of data-sets with their interactive visualisation.
(xarray can already load openDAP URLs directly, and Intake can provide such data sources, or interact with catalog or data services such as thredds which might list such resources)

**Comment by CommonClimate** [comment]
Thank you @hdsingh and @martindurant for your quick and informative answers. I had a look at the intake doc and it looks very promising. However, given the examples provided, I am not exactly sure how I would go about doing what you say (embedding the xrviz interface in a Panel).  If you have a notebook/example demonstrating that, I'd love to see it.

**Comment by martindurant** [comment]
Ah, I should have been clearer. Intake aims to embed the xrviz interface in its own GUI, but does not yet do so. Watch the space! For the time being, though, it may already be useful to you as a means of finding and loading your xarray (i.e., netcdf) data.

There are not yet any examples of how to embed xrviz in other applications, but there should eventually be. For the time being, I would advise you to read the Panel framework [documentation](https://panel.pyviz.org), and feel it should not be too difficult.

**Comment by CommonClimate** [comment]
Ah, my problem was that I am not plugged into the Python viz ecosystem, so didn't know about Panel as a package. After perusing the doc, it does seem like it's ideally suited to what we want to do. Do feel free to reach out if you need guinea pigs to test things out for you. 
Cheers

**Comment by martindurant** [comment]
Closing this as resolved, but please do follow our progress!
