### ISSUE TITLE
incorrect logger name

### ISSUE THREAD

**Issue by martindurant** [intake/xrviz#33]
See line https://github.com/intake/xrviz/blob/master/xrviz/sigslot.py#L5

**Comment by hdsingh** [comment]
Thanks for this issue. This will be corrected in https://github.com/intake/xrviz/pull/32 (since minor change is required).

**Comment by hdsingh** [comment]
@martindurant This has been corrected in #32. I think this issue can be closed now.

**Comment by hdsingh** [comment]
Since this issue has been resolved, I am closing it.
