### ISSUE TITLE
unpin holoviews in requirements.txt?

### ISSUE THREAD

**Issue by jhamman** [intake/xrviz#36]
Would it be possible to unpin holoviews? We're finding that using xrviz is making downstream package management at this time?

https://github.com/intake/xrviz/blob/e39c38a9004e445f52d611724f582c5b39c0da46/requirements.txt#L2

cc @scottyhq

**Comment by martindurant** [comment]
@hdsingh , is there any reason to keep this pin?

**Comment by hdsingh** [comment]
This specific version was added about 2 weeks ago to get correct lon/lat values on the hover. The latest version of holoviews doesn't show correct values. Everything else works fine with the latest version.

**Comment by hdsingh** [comment]
https://github.com/pyviz/holoviews/issues/3891

**Comment by jhamman** [comment]
This needs to be reopened.

**Comment by hdsingh** [comment]
This has been resolved in #48.
