### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/xrviz#42]
The latest release is 0.1, released July 16: https://github.com/intake/xrviz/releases

Time for a new release?

**Comment by martindurant** [comment]
@hdsingh , if you have a PYPI account, I can add you as a maintainer there, and you can do a release!

**Comment by martindurant** [comment]
There is also 0.1.1 from the end of July, but the tag didn't make it until just now. It is on pypi and conda-forge.

**Comment by hdsingh** [comment]
I have created an account on PYPI : [pypi.org/user/hdsingh/](https://pypi.org/user/hdsingh/).

**Comment by hdsingh** [comment]
@martindurant Thanks for adding me! I will go through this [guide](https://packaging.python.org/tutorials/packaging-projects/) to know more about making a release on pypi.

**Comment by martindurant** [comment]
I emailed you separately with instructions.

**Comment by hdsingh** [comment]
Thanks for the instructions. I will release `0.1.2` shortly.

**Comment by hdsingh** [comment]
The new release is available now (https://pypi.org/project/xrviz/#history).

**Comment by rsignell-usgs** [comment]
And on conda-forge!  Nice work!
![2019-09-05_7-02-56](https://user-images.githubusercontent.com/1872600/64341608-b63d9f00-cfb6-11e9-88f0-9af48f8ec046.png)
