### ISSUE TITLE
Return to dropdown selection selection of variables

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/xrviz#57]
I think the "start typing w/ autocomplete" is cool, but I think it's more intuitive (and even easier) to pick a variable from a drop down list, as we had before.   A new user (including me a few minutes ago) wouldn't know what to do when encountering this:
![2019-11-22_7-22-34](https://user-images.githubusercontent.com/1872600/69425813-a56d1180-0cf9-11ea-924f-34ddeb018f33.png)

**Comment by hdsingh** [comment]
I also think that with dropdown list it would become more natural and intuitive to  select a variable. I was also a bit unsure (just now when I looked it for first time) regarding next course of action.

Besides that this new xarray repr and addition of help in tabs is looking amazing!

**Comment by jsignell** [comment]
Sorry, I probably should have elevated that change more before merging it. I'll switch it back now.
