### ISSUE TITLE
Point binder button to great lakes notebook w/ presets

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/xrviz#58]
Let's point the binder button to the great lakes notebook, with presets enabled to give this display:
![2019-11-22_7-22-01](https://user-images.githubusercontent.com/1872600/69425940-ecf39d80-0cf9-11ea-8c30-c30e73104af4.png).   (I'm not sure whether we can preset station locations, but that would be pretty cool if we could)

**Comment by rsignell-usgs** [comment]
@hdsingh , is it possible to enable the time series plots via the `initial_params`?
(as in https://github.com/reproducible-notebooks/Explore-HRRR-with-XrViz/blob/master/HRRR_dashboard.ipynb)

**Comment by hdsingh** [comment]
The option to pass `extract along` in `initial_params` is available, however it is not working correctly (#60).
