### ISSUE TITLE
coastlines instead of basemap with initial_params

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/xrviz#62]
I tried to set the basemap to OSM via `initial_params` but got coastline instead.   @jsignell or @hdsingh do you see what's going wrong here:
![2019-11-27_8-21-20](https://user-images.githubusercontent.com/1872600/69727249-252b1f80-10f0-11ea-979f-b54ccd33ad96.png)
![2019-11-27_8-21-40](https://user-images.githubusercontent.com/1872600/69727254-28261000-10f0-11ea-8571-deb674b89401.png)
The actual notebook is here:
https://nbviewer.jupyter.org/gist/rsignell-usgs/2cb54811e7de391c30cbb9d34aa1a753

**Comment by jsignell** [comment]
I missed updating one bit when I merged #55. I'll open a PR
